CREATE TABLE IF NOT EXISTS etfs (
  symbol TEXT PRIMARY KEY,
  name TEXT
);

INSERT OR IGNORE INTO etfs (symbol, name) VALUES
('SPY', 'SPDR S&P 500 ETF Trust'),
('IVV', 'iShares Core S&P 500 ETF'),
('VOO', 'Vanguard S&P 500 ETF'),
('QQQ', 'Invesco QQQ Trust'),
('VTI', 'Vanguard Total Stock Market ETF'),
('VEA', 'Vanguard FTSE Developed Markets ETF'),
('IEFA', 'iShares Core MSCI EAFE ETF'),
('AGG', 'iShares Core U.S. Aggregate Bond ETF'),
('BND', 'Vanguard Total Bond Market ETF'),
('VUG', 'Vanguard Growth ETF'),
('VTV', 'Vanguard Value ETF'),
('BNDX', 'Vanguard Total International Bond ETF'),
('VXUS', 'Vanguard Total International Stock ETF'),
('IWF', 'iShares Russell 1000 Growth ETF'),
('IWD', 'iShares Russell 1000 Value ETF'),
('IJH', 'iShares Core S&P Mid-Cap ETF'),
('VIG', 'Vanguard Dividend Appreciation ETF'),
('VO', 'Vanguard Mid-Cap ETF'),
('VYM', 'Vanguard High Dividend Yield ETF'),
('XLF', 'Financial Select Sector SPDR Fund'),
('XLK', 'Technology Select Sector SPDR Fund'),
('XLE', 'Energy Select Sector SPDR Fund'),
('XLV', 'Health Care Select Sector SPDR Fund'),
('XLI', 'Industrial Select Sector SPDR Fund'),
('XLY', 'Consumer Discretionary Select Sector SPDR Fund'),
('XLP', 'Consumer Staples Select Sector SPDR Fund'),
('XLU', 'Utilities Select Sector SPDR Fund'),
('XLB', 'Materials Select Sector SPDR Fund'),
('VNQ', 'Vanguard Real Estate ETF'),
('SCHD', 'Schwab US Dividend Equity ETF'),
('RSP', 'Invesco S&P 500 Equal Weight ETF'),
('DIA', 'SPDR Dow Jones Industrial Average ETF Trust'),
('IWM', 'iShares Russell 2000 ETF'),
('VB', 'Vanguard Small-Cap ETF'),
('VGT', 'Vanguard Information Technology ETF'),
('QQQM', 'Invesco NASDAQ 100 ETF'),
('SOXX', 'iShares Semiconductor ETF'),
('SMH', 'VanEck Semiconductor ETF'),
('ARKK', 'ARK Innovation ETF'),
('JEPI', 'JPMorgan Equity Premium Income ETF');
